global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: glimmora-services
    metrics_path: /metrics
    static_configs:
      - targets:
          - auth-service:8000
          - contributor-service:8000
          - enterprise-service:8000
          - superadmin-service:8000
          - universities-service:8000
          - women-service:8000
          - mentor-service:8000
          - email-service:8000
          - file-service:8000
        labels:
          platform: glimmora
