import type { Blueprint, SOWIntelligence, SOWClause } from '@glimmora/types'

/**
 * Creates a deterministic mock blueprint with stable IDs for cross-panel synchronization.
 * Clause IDs in tasks match clause IDs in the intelligence data.
 */
export function createMockBlueprint(sowId: string): Blueprint {
  return {
    id: `bp-${sowId}`,
    sowId,
    projectName: 'Customer Engagement Platform',
    phases: [
      {
        id: 'phase-001',
        name: 'Discovery & Setup',
        description: 'Project kickoff, architecture design, and infrastructure setup',
        startDate: '2026-03-15',
        endDate: '2026-05-10',
        milestoneIds: ['ms-001', 'ms-002'],
      },
      {
        id: 'phase-002',
        name: 'Core Development',
        description: 'Core platform features, mobile apps, and analytics dashboard',
        startDate: '2026-05-11',
        endDate: '2026-07-26',
        milestoneIds: ['ms-003', 'ms-004'],
      },
    ],
    milestones: [
      {
        id: 'ms-001',
        name: 'Architecture & Infrastructure',
        description: 'Complete system architecture, CI/CD pipeline, and cloud infrastructure',
        successCriteria: 'All infrastructure deployed, CI/CD green, staging environment accessible',
        taskIds: ['task-001', 'task-002', 'task-003'],
        budgetAllocation: 45000,
        targetWeek: 3,
        paymentTrigger: 'auto-on-approval',
      },
      {
        id: 'ms-002',
        name: 'Core Platform MVP',
        description: 'User authentication, core API, and admin dashboard',
        successCriteria: 'Users can register, login, and access dashboard with live data',
        taskIds: ['task-004', 'task-005'],
        budgetAllocation: 55000,
        targetWeek: 6,
        paymentTrigger: 'manual',
      },
      {
        id: 'ms-003',
        name: 'Mobile & Analytics',
        description: 'Mobile applications and analytics dashboard with real-time data',
        successCriteria: 'Mobile apps pass QA, analytics dashboard shows live metrics',
        taskIds: ['task-006', 'task-007', 'task-008'],
        budgetAllocation: 85000,
        targetWeek: 12,
        paymentTrigger: 'auto-on-approval',
      },
      {
        id: 'ms-004',
        name: 'Integration & Launch',
        description: 'Third-party integrations, UAT, and production deployment',
        successCriteria: 'All integrations tested, UAT signed off, production deployed',
        taskIds: ['task-009', 'task-010'],
        budgetAllocation: 65000,
        targetWeek: 16,
        paymentTrigger: 'manual',
      },
    ],
    tasks: [
      {
        id: 'task-001',
        title: 'System Architecture Design',
        description: 'Design the overall system architecture including microservices, data flow, and deployment topology',
        skillRequirements: ['system-design', 'cloud-architecture', 'microservices'],
        estimatedHours: 40,
        evidenceTypeExpected: 'document',
        acceptanceCriteria: 'Architecture document approved by tech lead with deployment diagram',
        dependsOn: [],
        clauseIds: ['clause-001'],
      },
      {
        id: 'task-002',
        title: 'Real-Time Analytics Pipeline',
        description: 'Build real-time data pipeline with sub-second refresh for key business metrics',
        skillRequirements: ['data-engineering', 'apache-kafka', 'postgresql', 'typescript'],
        estimatedHours: 60,
        evidenceTypeExpected: 'code',
        acceptanceCriteria: 'Dashboard refreshes within 1 second, handles 10K concurrent events',
        dependsOn: ['task-001'],
        clauseIds: ['clause-001'],
      },
      {
        id: 'task-003',
        title: 'Security & Compliance Setup',
        description: 'Implement AES-256 encryption at rest, TLS 1.3 in transit, and SOC 2 Type II controls',
        skillRequirements: ['security', 'compliance', 'devops', 'encryption'],
        estimatedHours: 48,
        evidenceTypeExpected: 'document',
        acceptanceCriteria: 'Encryption verified, TLS 1.3 enforced, audit log active',
        dependsOn: ['task-001'],
        clauseIds: ['clause-002'],
      },
      {
        id: 'task-004',
        title: 'Web Application Frontend',
        description: 'Build responsive web application with React, including dashboard, settings, and user management',
        skillRequirements: ['react', 'typescript', 'ui-design', 'accessibility'],
        estimatedHours: 80,
        evidenceTypeExpected: 'code',
        acceptanceCriteria: 'All pages responsive, WCAG 2.1 AA compliant, performance score > 90',
        dependsOn: ['task-001', 'task-002'],
        clauseIds: ['clause-003'],
      },
      {
        id: 'task-005',
        title: 'API Gateway & Core Backend',
        description: 'Build REST API gateway with authentication, rate limiting, and core business logic',
        skillRequirements: ['node.js', 'typescript', 'api-design', 'postgresql'],
        estimatedHours: 72,
        evidenceTypeExpected: 'code',
        acceptanceCriteria: 'API documented, 95% test coverage, handles 1K req/s',
        dependsOn: ['task-001'],
        clauseIds: ['clause-003', 'clause-001'],
      },
      {
        id: 'task-006',
        title: 'iOS Native Application',
        description: 'Build iOS native app with feature parity to web application',
        skillRequirements: ['swift', 'ios', 'mobile-development'],
        estimatedHours: 96,
        evidenceTypeExpected: 'code',
        acceptanceCriteria: 'Feature parity with web, App Store review guidelines met',
        dependsOn: ['task-005'],
        clauseIds: ['clause-003'],
      },
      {
        id: 'task-007',
        title: 'Android Native Application',
        description: 'Build Android native app with feature parity to web application',
        skillRequirements: ['kotlin', 'android', 'mobile-development'],
        estimatedHours: 96,
        evidenceTypeExpected: 'code',
        acceptanceCriteria: 'Feature parity with web, Play Store guidelines met',
        dependsOn: ['task-005'],
        clauseIds: ['clause-003'],
      },
      {
        id: 'task-008',
        title: 'Analytics Dashboard Integration',
        description: 'Integrate real-time analytics dashboard with charts, KPIs, and data export',
        skillRequirements: ['react', 'data-visualization', 'typescript'],
        estimatedHours: 56,
        evidenceTypeExpected: 'code',
        acceptanceCriteria: 'Dashboard loads in < 2s, all KPIs render correctly, export to CSV works',
        dependsOn: ['task-002', 'task-004'],
        clauseIds: ['clause-001'],
      },
      {
        id: 'task-009',
        title: 'Third-Party Integrations',
        description: 'Integrate with payment gateway, email service, and CRM system',
        skillRequirements: ['api-integration', 'node.js', 'typescript'],
        estimatedHours: 48,
        evidenceTypeExpected: 'code',
        acceptanceCriteria: 'All integrations tested with sandbox environments, error handling verified',
        dependsOn: ['task-005'],
        clauseIds: ['clause-006'],
      },
      {
        id: 'task-010',
        title: 'UAT & Production Deployment',
        description: 'User acceptance testing, performance testing, and production deployment',
        skillRequirements: ['devops', 'testing', 'cloud-deployment'],
        estimatedHours: 40,
        evidenceTypeExpected: 'document',
        acceptanceCriteria: 'UAT signed off, load test passed, production monitoring active',
        dependsOn: ['task-004', 'task-006', 'task-007', 'task-008', 'task-009'],
        clauseIds: ['clause-004'],
      },
    ],
    totalBudget: 250000,
    timeline: { startDate: '2026-03-15', endDate: '2026-07-26' },
    completionPercentage: 0,
    issues: [],
    status: 'draft',
  }
}

/**
 * Creates deterministic SOW intelligence with stable clause IDs that match blueprint task clauseIds.
 */
export function createMockBlueprintIntelligence(sowId: string): SOWIntelligence {
  const clauses: SOWClause[] = [
    {
      id: 'clause-001',
      text: 'The platform shall provide real-time analytics dashboards with sub-second refresh rates for key business metrics.',
      type: 'objective',
      confidence: 0.94,
      linkedTaskIds: ['task-001', 'task-002', 'task-005', 'task-008'],
    },
    {
      id: 'clause-002',
      text: 'All customer data must be encrypted at rest (AES-256) and in transit (TLS 1.3) per SOC 2 Type II requirements.',
      type: 'compliance',
      confidence: 0.98,
      linkedTaskIds: ['task-003'],
    },
    {
      id: 'clause-003',
      text: 'Deliver a responsive web application, iOS native app, and Android native app with feature parity.',
      type: 'deliverable',
      confidence: 0.91,
      linkedTaskIds: ['task-004', 'task-005', 'task-006', 'task-007'],
    },
    {
      id: 'clause-004',
      text: 'Phase 1 deliverables due within 8 weeks of project kickoff; Phase 2 within 16 weeks.',
      type: 'timeline',
      confidence: 0.89,
      linkedTaskIds: ['task-010'],
    },
    {
      id: 'clause-005',
      text: 'Total project budget not to exceed $250,000 USD inclusive of all development, testing, and deployment costs.',
      type: 'budget',
      confidence: 0.96,
      linkedTaskIds: [],
    },
    {
      id: 'clause-006',
      text: 'The vendor shall provide 12 months of post-launch support including bug fixes, third-party integration maintenance, and minor feature enhancements.',
      type: 'general',
      confidence: 0.85,
      linkedTaskIds: ['task-009'],
    },
  ]

  return {
    sowId,
    projectObjective:
      'Build and deploy a cloud-native customer engagement platform with real-time analytics, AI-powered personalization, and multi-channel communication capabilities.',
    clauses,
    deliverables: [
      { text: 'Web application with analytics dashboard', included: true },
      { text: 'iOS native mobile application', included: true },
      { text: 'Android native mobile application', included: true },
      { text: 'API documentation and integration guide', included: true },
      { text: 'Load testing and performance report', included: false },
    ],
    timelineEstimates: [
      { milestone: 'Project Kickoff & Architecture', date: '2026-03-15' },
      { milestone: 'Phase 1: Core Platform MVP', date: '2026-05-10' },
      { milestone: 'Phase 2: Mobile Apps & Analytics', date: '2026-07-05' },
      { milestone: 'UAT & Launch Preparation', date: '2026-07-26' },
    ],
    budgetRange: { min: 200000, max: 250000, currency: 'USD' },
    complianceFlags: [
      { item: 'SOC 2 Type II certification required for data handling', severity: 'mandatory' },
      { item: 'GDPR compliance for EU customer data processing', severity: 'mandatory' },
    ],
    confidenceScore: 0.87,
    ambiguities: [
      {
        section: 'Post-launch Support',
        issue: 'Scope of "minor feature enhancements" is not quantified -- could lead to scope creep disputes.',
      },
    ],
  }
}
